### PR TITLE
fix mingw compat

### PR DESCRIPTION
**Pull request by SobhanMP**
see https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=20791&view=logs&jobId=eb643228-59a0-57e5-a6a5-6cb55400d5ea&j=26a97fd6-2070-5ccc-98fe-466416439df2&t=abe13601-88ab-5e8d-6817-533311385b0c

### CODE REVIEW

**Comment by SobhanMP** [comment]
now it looks like 

https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=20793&view=logs&jobId=eb643228-59a0-57e5-a6a5-6cb55400d5ea

**Review by ctribes — COMMENTED** [review]
MicrosSleep.hpp is problematic.

```
#ifdef _WIN32
#include <chrono>
#include <thread>

static inline void usleep(uint64_t usec) {
    std::this_thread::sleep_for(std::chrono::microseconds(usec));
}

#else
#include <unistd.h>
#endif
```

My guess is that the usleep is defined twice when compiling in MinGW.
I cannot test it rapidly but I would change `#ifdef _WIN32` by `#ifdef _MSC_VER`

**Comment by SobhanMP** [comment]
it still fails at the link phase (same as explicitly defining 10 as unsigned)

**Comment by SobhanMP** [comment]
```
[16:01:39] /opt/x86_64-w64-mingw32/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/nomadEval.dir/objects.a(CacheBase.cpp.obj):CacheBase.cpp:(.text+0x342): undefined reference to `NOMAD_4_2::toupper(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
[16:01:39] /opt/x86_64-w64-mingw32/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/nomadEval.dir/objects.a(CacheBase.cpp.obj):CacheBase.cpp:(.text+0x3e6): undefined reference to `NOMAD_4_2::toupper(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
[16:01:39] /opt/x86_64-w64-mingw32/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/nomadEval.dir/objects.a(CacheBase.cpp.obj):CacheBase.cpp:(.text+0x454): undefined reference to `NOMAD_4_2::isAbsolute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
[16:01:39] /opt/x86_64-w64-mingw32/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/nomadEval.dir/objects.a(CacheBase.cpp.obj):CacheBase.cpp:(.text+0x6fa): undefined reference to `NOMAD_4_2::CacheParameters::init()'
[16:01:39] /opt/x86_64-w64-mingw32/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/nomadEval.dir/objects.a(CacheBase.cpp.obj):CacheBase.cpp:(.text$_ZNK9NOMAD_4_210Parameters10getSpValueIyEERKT_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbb[_ZNK9NOMAD_4_210Parameters10getSpValueIyEERKT_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbb]+0xa3): undefined reference to `NOMAD_4_2::Parameters::getAttribute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const'
[16:01:39] /opt/x86_64-w64-mingw32/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/nomadEval.dir/objects.a(CacheBase.cpp.obj):CacheBase.cpp:(.text$_ZNK9NOMAD_4_210Parameters10getSpValueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEERKT_RKS7_bb[_ZNK9NOMAD_4_210Parameters10getSpValueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEERKT_RKS7_bb]+0xa3): undefined reference to `NOMAD_4_2::Parameters::getAttribute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const'
[16:01:39] /opt/x86_64-w64-mingw32/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/nomadEval.dir/objects.a(CacheBase.cpp.obj):CacheBase.cpp:(.rdata$_ZTVN9NOMAD_4_220ParameterToBeCheckedE[_ZTVN9NOMAD_4_220ParameterToBeCheckedE]+0x20): undefined reference to `NOMAD_4_2::Exception::what() const'
[16:01:39] /opt/x86_64-w64-mingw32/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/nomadEval.dir/objects.a(CacheBase.cpp.obj):CacheBase.cpp:(.rdata$.refptr._ZTVN9NOMAD_4_215CacheParametersE[.refptr._ZTVN9NOMAD_4_215CacheParametersE]+0x0): undefined reference to `vtable for NOMAD_4_2::CacheParameters'
[16:01:39] /opt/x86_64-w64-mingw32/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/nomadEval.dir/objects.a(CacheBase.cpp.obj):CacheBase.cpp:(.rdata$.refptr._ZTVN9NOMAD_4_29ExceptionE[.refptr._ZTVN9NOMAD_4_29ExceptionE]+0x0): undefined reference to `vtable for NOMAD_4_2::Exception'
```

**Review by amontoison — APPROVED** [review]

**Comment by ctribes** [comment]
I will install mingw to see what should be done.

**Comment by SobhanMP** [comment]
thanks!

**Pull request closed without merging**
